### ISSUE TITLE
Travis purge cache & rebuild master

### ISSUE THREAD

**Issue by matthew-andrews** [Financial-Times/next-build-tools#51]
```
next-build-tools rebuild # defaults to purge cache, ~~current git branch*~~ master, current app
next-build-tools rebuild <repo-name/app-name/aircraft-name**> # defaults to purge cache, master
next-build-tools rebuild <repo-name/app-name/aircraft-name**>  --keep-cache --branch master
```

\* ~~not sure about this.~~
\** grumman => next-grumman, ft-next-grumman => next-grumman, next-grumman => next-grumman (travis is indexed by `next-{{plane}}`)

**Comment by matthew-andrews** [comment]
nb. Travis only.

**Comment by wheresrhys** [comment]
Yep looks good

If possible should stop any current build of that commit too.

Related idea for component rolling out:

```
next-component-tools rollout
```

Which

1. Checks service registry for apps serving type `next-page`
2. calls `next-build-tools rebuild app-name` for each of those

Need to think about QA of this eventually. I also wonder if it might not be better to create a new dummy commit wit the message `rolling out component-x at version l.n.m` instead of just a rebuild. 

Longer term I think we'd want to rate limit how much this can happen. Maybe `nct rollout` pings a service which queues builds sensibly (e.g. checks to see when the last build was) instead of triggering the build directly. And this could run as the deploy step of components' CI

**Comment by matthew-andrews** [comment]
done!
